---
kind: pipeline
type: docker

steps:
  - name: Build
    image: haxe:4.2.1
    commands:
      - haxelib install --always all.hxml
      - haxe all.hxml
  - name: Tests in NodeJS
    image: node:alpine
    commands:
      - node bin/tests.js
    depends_on:
      - Build
  - name: Tests in PHP7
    image: php:7.0-cli-alpine
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build
  - name: Tests in PHP8
    image: php:8.0-cli-alpine
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build  
  - name: Tests in Neko
    image: haxe:4.2.1
    commands:
      - neko ./bin/tests.n
    depends_on:
      - Build
  - name: Tests in Python
    image: python:alpine
    commands:
      - python ./bin/tests.py
    depends_on:
      - Build
  - name: Build Documentation
    image: haxe:4.2.1
    commands:
      - haxelib install --always documentation.hxml
      - haxe documentation.hxml
    depends_on:
      - Tests in NodeJS
      - Tests in PHP7
      - Tests in PHP8
      - Tests in Neko
      - Tests in Python
  - name: Publish Documentation
    image: plugins/s3-sync:1
    settings:
      bucket: roll-man
      access_key: 
        from_secret: minio_access_key
      secret_key: 
        from_secret: minio_secret_key
      source: docs/pages
      target: /docs
      path_style: true
      endpoint: https://minio.thomaslucas.co.uk
      delete: true
    depends_on:
      - Build Documentation
---
kind: signature
hmac: a26fa0cd811639d55d4664bd17238fc804f13d50164d902b2dd949872d74397c

...
