---
kind: pipeline
type: docker
name: Run Tests

platform:
  os: linux
  arch: arm

steps:
  - name: NullSafe Build
    image: haxe:4.2.3
    commands:
      - haxelib install --always --quiet build-nullsafe.hxml
      - haxe build-nullsafe.hxml
  - name: Build
    image: haxe:4.2.3
    commands:
      - haxelib install --always --quiet all.hxml
      - haxe all.hxml
    depends_on:
      - NullSafe Build
  - name: Check Style
    image: haxe:4.2.3
    commands:
      - haxelib install --always --quiet checkstyle
      - haxelib run checkstyle -s src --exitcode
    depends_on:
      - Build
  - name: Tests in NodeJS
    image: node:16.3.0-alpine3.13
    commands:
      - node bin/tests.js
    depends_on:
      - Build
  - name: Tests in PHP7
    image: php:7.4-cli-alpine3.13
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build
  - name: Tests in PHP8
    image: php:8.0-cli-alpine3.13
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build  
  - name: Tests in Neko
    image: haxe:4.2.3
    commands:
      - neko ./bin/tests.n
    depends_on:
      - Build
  - name: Tests in Python
    image: python:3.7-alpine3.13
    commands:
      - python ./bin/tests.py
    depends_on:
      - Build
---
kind: pipeline
name: Publish Documentation

platform:
  os: linux
  arch: arm

steps:
  - name: Generate Code Coverage Badge
    image: node:16.3.0-alpine3.13
    commands:
      - npm i -g lcov-badge2
      - lcov-badge2 ./lcov.info
    depends_on:
      - Tests in NodeJS
      - Tests in PHP7
      - Tests in PHP8
      - Tests in Neko
      - Tests in Python
      - Check Style
  - name: Update Online Coverage Badge
    image: plugins/s3
    settings:
      bucket: haxe-dice
      access_key: 
        from_secret: minio_access_key
      secret_key: 
        from_secret: minio_secret_key
      source: badge.svg
      target: /coverage
      path_style: true
      endpoint: https://minio.thomaslucas.co.uk
    depends_on:
      - Generate Code Coverage Badge
      - master
  - name: Build Documentation
    image: haxe:4.2.3
    commands:
      - haxelib install --always --quiet documentation.hxml
      - haxe documentation.hxml
    depends_on:
      - Tests in NodeJS
      - Tests in PHP7
      - Tests in PHP8
      - Tests in Neko
      - Tests in Python
      - Check Style
  - name: Publish Documentation
    image: plugins/s3
    settings:
      bucket: haxe-dice
      access_key: 
        from_secret: minio_access_key
      secret_key: 
        from_secret: minio_secret_key
      source: docs/pages/**/*
      target: /
      path_style: true
      endpoint: https://minio.thomaslucas.co.uk
    depends_on:
      - Build Documentation

trigger:
  branch:
  - master

depends_on:
- Run Tests
---
kind: pipeline
name: Release

platform:
  os: linux
  arch: arm

steps:
  - name: Zip Library
    image: alpine:3.15.2
    commands:
      - apk add zip jq
      - cat haxelib.json | jq -r ". += {\"version\":\"${DRONE_TAG}\"}" > tmp && mv tmp haxelib.json
      - zip -r library.zip src *.md haxelib.json
  - name: Haxelib Publish
    image: haxe:4.2.4
    commands:
      - haxelib submit library.zip $HAXELIB_PASSWORD --always
    environment:
      HAXELIB_PASSWORD:
        from_secret: HAXELIB_PASSWORD

trigger:
  event:
  - tag

depends_on:
- Run Tests
---
kind: signature
hmac: d68087dd1903dc57995f89fd2ff9c3c7b7e0a507873bdae848c991b622a6eeb7

...
