---
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

steps:
  - name: Build
    image: haxe:4.2.3
    commands:
      - haxelib install --always all.hxml
      - haxe all.hxml
  - name: Tests in NodeJS
    image: node:16.3.0-alpine3.13
    commands:
      - node bin/tests.js
    depends_on:
      - Build
  - name: Tests in PHP7
    image: php:7.4-cli-alpine3.13
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build
  - name: Tests in PHP8
    image: php:8.0-cli-alpine3.13
    commands:
      - php ./bin/php-tests/index.php
    depends_on:
      - Build  
  - name: Tests in Neko
    image: haxe:4.2.3
    commands:
      - neko ./bin/tests.n
    depends_on:
      - Build
  - name: Tests in Python
    image: python:3.7-alpine3.13
    commands:
      - python ./bin/tests.py
    depends_on:
      - Build
  - name: Build Documentation
    image: haxe:4.2.3
    commands:
      - haxelib install --always documentation.hxml
      - haxe documentation.hxml
    depends_on:
      - Tests in NodeJS
      - Tests in PHP7
      - Tests in PHP8
      - Tests in Neko
      - Tests in Python
  - name: Publish Documentation
    image: plugins/s3
    settings:
      bucket: roll-man
      access_key: 
        from_secret: minio_access_key
      secret_key: 
        from_secret: minio_secret_key
      source: docs/pages/**/*
      target: /
      path_style: true
      endpoint: https://minio.thomaslucas.co.uk
    depends_on:
      - Build Documentation
---
kind: signature
hmac: 56d377e2cc741f5c0f57df904fb3d15c7ed37c146f5e4d3d0b9768f7fdfe94c4

...
